import { ReactNode, Suspense } from "react";
import { Metadata } from "next";

import ChatLayout from "./ChatLayout";
import Loader from "@/components/ui/Loader";

export const metadata: Metadata = {
  title: {
    default: "Chat",
    template: "%s | Shatter",
  },
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <Suspense fallback={<Loader />}>
      <ChatLayout>{children}</ChatLayout>
    </Suspense>
  );
};

export default Layout;
