import { ReactNode } from "react";
import { Metadata } from "next";

import ChatLayout from "./ChatLayout";

export const metadata: Metadata = {
  title: {
    default: "Chat",
    template: "%s | Shatter",
  },
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: ReactNode }) => {
  return <ChatLayout>{children}</ChatLayout>;
};

export default Layout;
